### ISSUE TITLE
Some mods download with %20 in the filename

### ISSUE THREAD

**Issue by ngraham20** [ngraham20/facmod-rs#3]

**Comment by cliftontoaster-reid** [comment]
Upon identifying the issue at hand, I promptly took appropriate action. The primary cause of this issue is the extraction of the name from the URL, which frequently leads to the name containing characters that are not compatible with the URI standard. In this particular case, a space character was replaced with %20. To rectify this, I employed the 'urlencoding' crate to decode the name, anticipating that this will resolve the issue. I hope this explanation has been beneficial in understanding the situation. A pull request containing the fix should be available at the time of this message.

@ngraham20

**Comment by ngraham20** [comment]
Sweet, thanks for the PR!
